name: Build & Release Must Murder Mommy

on:
  release:
    types: [published]  # Triggers when a GitHub release is created

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🧰 Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

            - name: 📦 Install Required HaxeLibs
        run: |
          haxelib setup C:\HaxeToolkit\haxelib
          haxelib install lime 2.9.1
          haxelib install openfl 3.6.1
          haxelib install flixel 4.4.1
          haxelib install flixel-addons 2.6.0
          haxelib install flixel-ui 2.3.0
          haxelib install nape
          haxelib install hxcpp
          haxelib git hscript https://github.com/HaxeFoundation/hscript

      - name: 🔧 Setup hxcpp toolchain
        run: haxelib run hxcpp

      - name: 🛠️ Build Windows Release
        run: haxelib run lime build Project.xml windows -release

      - name: 🌐 Build HTML5 Release
        run: haxelib run lime build Project.xml html5 -release

      - name: 📦 Package Windows Build
        run: |
          powershell Compress-Archive -Path export/release/windows/bin/* -DestinationPath mommyGF-windows.zip

      - name: 📦 Package HTML5 Build
        run: |
          powershell Compress-Archive -Path export/release/html5/bin/* -DestinationPath mommyGF-html5.zip

      - name: 🚀 Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mommyGF-windows.zip
            mommyGF-html5.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
